on: push

name: TOC Generator

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: ""
          TARGET_PATHS: "README*.md,CONTRIBUTING.md"
